# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pick',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
